name: Manually triggered workflow
on: workflow_dispatch

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.18.4
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.4
      - name: npm install, build, and test
        run: |
          # Build and test the project, then
          # deploy to Azure Web App.
          npm ci
          npm run build --if-present

      # copy files to scp
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          password: ${{ secrets.DO_PW }}
          port: 22
          source: "."
          target: "/var/www"

      - name: Executing remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          password: ${{ secrets.DO_PW }}
          port: 22
          script: |
            setup_server.sh
            npm install
            npm start
